---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: set_custom_attributes
    inherits: 
    description: 
  fields:
  - method1:
      value: set_custom_attributes
